In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
mul = np.matmul

In [34]:
opt_train = pd.read_csv('optdigits.tra',header=None)

In [35]:
opt_train.head()

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,0,1,6,15,12,1,0,0,0,7,...,0,0,0,6,14,7,1,0,0,0
1,0,0,10,16,6,0,0,0,0,7,...,0,0,0,10,16,15,3,0,0,0
2,0,0,8,15,16,13,0,0,0,1,...,0,0,0,9,14,0,0,0,0,7
3,0,0,0,3,11,16,0,0,0,0,...,0,0,0,0,1,15,2,0,0,4
4,0,0,5,14,4,0,0,0,0,0,...,0,0,0,4,12,14,7,0,0,6

In [36]:
X= pd.concat([pd.Series(1, index=opt_train.index, name='00'), opt_train.iloc[:,:64]], axis=1)

In [37]:
y = opt_train.iloc[:,64]

In [38]:
y1 = np.zeros([opt_train.shape[0], len(y.unique())])
y1 = pd.DataFrame(y1)

In [39]:
for i in range(0, len(y.unique())):
    for j in range(0, len(y1)):
        if y[j] == y.unique()[i]:
            y1.iloc[j, i] = 1
        else: 
            y1.iloc[j, i] = 0
#y1.head()

In [40]:
def sigmoid(X):
    return 1/(1+np.exp(-(X)))

In [59]:
def hypothesis(X, theta):
    z = np.dot(X, theta)
    return sigmoid(z)

In [42]:
def computeCost(theta, X, y, lamda=None):
    m = X.shape[0]
    if lamda:
        return (1/m) * mul(X.T, (hypothesis(X, theta) - y)) + (lamda/m) * theta 
    return (1/m) * mul(X.T, (hypothesis(X, theta) - y))

In [43]:
def update_theta(theta, X, y, alpha, lamda=None):
    return theta - alpha * computeCost(theta, X, y, lamda)

In [53]:
def gradient_descent(X, y, theta, alpha, epochs, lamda=None):
    m = len(X)
    for i in range(0, epochs):
        for j in range(0, 10):
            theta = pd.DataFrame(theta)
            h = hypothesis(X,theta.iloc[:,j])
            for k in range(0, theta.shape[0]):
                theta.iloc[k, j] = update_theta(theta.iloc[k, j],X.iloc[:, k],y.iloc[:, j],alpha,lamda)
            theta = pd.DataFrame(theta)
    return theta

In [60]:
theta = np.zeros([X.shape[1], y1.shape[1]])
theta = gradient_descent(X, y1, theta, 0.01, 1500,lamda=0.5)

In [61]:
X.shape

(3823, 65)

In [62]:
y.shape

(3823,)

In [63]:
theta

,0,1,2,3,4,5,6,7,8,9
0,-1.881386,-1.862883,-1.862883,-1.879699,-1.874643,-1.881386,-1.874643,-1.859532,-1.871278,-1.859532
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,-0.949911,-0.634066,-0.959715,-0.969564,-0.278614,-0.568814,-0.845049,-0.962173,-0.842730,-0.336980
3,-0.318464,-0.233341,-0.724014,-0.492046,-0.169786,-0.215145,-0.278097,-0.456700,-0.286558,-0.193350
4,-0.163211,-0.159263,-0.231129,-0.181730,-0.156848,-0.164514,-0.165931,-0.195804,-0.170543,-0.154753
...,...,...,...,...,...,...,...,...,...,...
60,-0.159330,-0.174297,-0.218186,-0.182231,-0.155048,-0.154063,-0.159439,-0.197936,-0.166523,-0.149842
61,-0.155882,-0.370080,-0.168443,-0.146946,-0.155753,-0.177346,-0.159429,-0.158137,-0.165291,-0.154674
62,-0.240532,-1.048665,-0.356900,-0.131773,-0.137147,-0.309014,-0.211542,-0.172215,-0.208982,-0.193221
63,-0.930537,-1.101122,-1.013036,-0.115208,-0.033080,-0.762972,-0.513411,-0.263227,-0.366026,-0.421570
64,-0.540381,-0.540381,-0.523053,-0.334774,0.056687,-0.535402,-0.523053,-0.176483,-0.518154,-0.535402

In [65]:
output = []
for i in range(0, 10):
    theta1 = pd.DataFrame(theta)
    h = hypothesis(X,theta1.iloc[:,i])
    output.append(h)
output=pd.DataFrame(output)

In [66]:
output

,0,1,2,3,4,5,6,7,8,9,...,3813,3814,3815,3816,3817,3818,3819,3820,3821,3822
0,1.491668e-26,4.040565e-31,2.512239e-40,1.361312e-38,1.898127e-27,2.190006e-47,2.937365e-29,1.971262e-31,9.208025e-35,1.223010e-44,...,2.210002e-26,5.146818e-40,7.755180e-42,3.304158e-40,5.047423e-28,1.322358e-29,1.679076e-29,8.125773e-37,2.347161e-38,2.522691e-34
1,6.582891e-42,1.113834e-56,3.556940e-25,5.223829e-35,5.759637e-44,3.365404e-56,2.913670e-30,2.237352e-34,3.916426e-45,9.265417e-59,...,6.007474e-36,2.071609e-34,3.460826e-60,2.447234e-48,2.623380e-40,1.830769e-41,9.244253e-37,7.291861e-45,1.046485e-61,3.123771e-19
2,8.760559e-36,4.495081e-45,3.906683e-33,2.483328e-28,1.263096e-31,1.525356e-50,1.995919e-26,4.042989e-31,2.029374e-39,3.890673e-46,...,6.172931e-22,8.415900e-36,1.616036e-51,1.587114e-43,1.110058e-33,6.313951e-36,9.775773e-21,3.041295e-31,4.380492e-42,1.892932e-25
3,4.334858e-43,3.770958e-55,2.245946e-45,1.449815e-51,9.295986e-24,2.158706e-46,3.068754e-45,1.418016e-36,1.516405e-55,5.285344e-45,...,3.793956e-30,1.847361e-49,8.773644e-52,3.278327e-47,5.885608e-38,5.744804e-41,2.975153e-29,3.196561e-26,1.052280e-30,5.947315e-47
4,3.496047e-44,1.628140e-58,3.313700e-39,1.811002e-44,3.767639e-34,2.391168e-31,5.393829e-38,2.076303e-31,2.197653e-57,1.861680e-44,...,9.778119e-39,4.024478e-36,4.601001e-47,3.973747e-36,4.224696e-30,3.362057e-37,9.683975e-42,2.508697e-38,2.569192e-47,5.958402e-39
5,1.839633e-36,1.798302e-48,1.358666e-35,2.046437e-34,3.201630e-28,1.905601e-41,4.457748e-29,8.483111e-24,1.206752e-44,7.820324e-40,...,1.823022e-35,7.414381e-41,5.778302e-46,7.719124e-35,8.356046e-29,2.647592e-32,4.559188e-37,3.452386e-35,5.981648e-43,1.907137e-31
6,2.687859e-34,4.456733e-46,1.338929e-30,3.242085e-31,7.020056e-27,1.031211e-35,1.977177e-28,2.483248e-25,9.988956e-41,9.683216e-37,...,1.636039e-30,1.202797e-28,6.411069e-41,5.699002e-33,3.567743e-26,1.221102e-29,1.449596e-31,1.420950e-29,3.076317e-39,6.059515e-27
7,1.035155e-40,7.900214e-54,8.574299e-33,1.570635e-31,2.912260e-30,9.173423e-36,8.476388e-28,6.270303e-27,3.149998e-48,5.276056e-42,...,5.665180e-34,8.999100e-34,6.270292e-48,8.274923e-41,1.403862e-30,8.270671e-36,9.185982e-32,1.114503e-32,6.413753e-43,2.990698e-30
8,1.029180e-35,1.571489e-45,1.407174e-35,3.137587e-27,2.078055e-30,1.852972e-35,1.898737e-23,3.987931e-24,1.607256e-41,8.997075e-40,...,6.737478e-40,4.913844e-37,5.747680e-35,3.518043e-33,1.122478e-23,1.296945e-23,7.045447e-43,2.128326e-39,1.368412e-47,7.004628e-23
9,4.547423e-42,9.195400e-56,2.510042e-36,1.509372e-39,1.169927e-33,3.281646e-37,8.517752e-32,1.426242e-28,8.609045e-51,4.005644e-44,...,1.175673e-43,9.753698e-41,2.254331e-38,1.723891e-29,1.237596e-24,4.390969e-28,1.238297e-47,8.050304e-40,1.094192e-51,6.728968e-28

In [67]:
accuracy = 0
for col in range(0, 10):
    for row in range(len(y1)):
        if y1.iloc[row, col] == 1 and output.iloc[col, row] >= 0.5:
            accuracy += 1
accuracy = accuracy/len(X)

In [68]:
accuracy

0.0

In [69]:
df_test = pd.read_csv('optdigits.tes',header=None)
df_test_feat = df_test.iloc[:,:64]
df_test_out = df_test.iloc[:,64]
X_test= pd.concat([pd.Series(1, index=df_test_feat.index, name='00'), df_test_feat], axis=1)
y_test = np.zeros([df_test_out.shape[0], len(df_test_out.unique())])
y_test = pd.DataFrame(y_test)

In [70]:
for i in range(0, len(df_test_out.unique())):
    for j in range(0, len(y_test)):
        if df_test_out[j] == df_test_out.unique()[i]:
            y_test.iloc[j, i] = 1
        else: 
            y_test.iloc[j, i] = 0
y_test

        0    1    2    3    4    5    6    7    8    9
0     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
1792  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
1793  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1794  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
1795  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
1796  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0

[1797 rows x 10 columns]

In [71]:
output_test = []
for i in range(0, 10):
    theta1 = pd.DataFrame(theta)
    h = hypothesis(X_test,theta1.iloc[:,i])
    output_test.append(h)
output_test=pd.DataFrame(output_test)

In [72]:
output_test

,0,1,2,3,4,5,6,7,8,9,...,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796
0,1.111438e-24,1.921894e-42,1.160398e-44,1.264227e-33,4.632571e-27,3.889051e-38,5.509565e-34,6.502660e-46,7.455279e-43,3.356093e-36,...,5.138654e-33,7.727474e-36,1.106056e-47,5.150607e-44,4.020162e-38,6.140874e-36,1.890753e-34,3.461211e-45,1.226534e-36,1.207951e-47
1,4.254271e-38,2.053903e-38,1.173635e-49,2.472509e-42,5.027030e-33,1.013146e-47,3.048734e-46,1.602725e-22,1.385764e-47,5.303945e-44,...,3.054309e-43,1.371264e-47,9.273672e-38,7.692244e-35,3.794026e-45,1.038331e-44,2.727063e-51,7.047118e-44,1.995641e-46,3.042818e-57
2,4.823910e-31,2.664961e-28,1.473838e-36,2.991249e-36,8.421517e-20,5.495168e-39,6.043260e-30,3.723805e-34,1.130982e-39,6.544674e-38,...,5.901511e-34,1.065491e-26,4.763560e-37,1.347864e-32,2.430296e-26,6.916909e-37,2.629582e-40,2.948828e-33,6.052195e-35,1.777387e-43
3,8.935217e-45,2.081747e-36,3.394285e-43,6.369068e-33,1.724613e-29,1.363798e-43,3.006997e-24,1.647898e-54,5.958312e-44,2.754195e-43,...,2.149063e-34,1.455399e-39,1.513993e-47,1.027579e-43,2.242906e-39,1.630133e-49,2.897855e-53,4.542437e-43,2.073606e-47,5.604274e-46
4,1.334157e-46,6.499322e-31,1.124420e-35,7.022418e-28,1.476544e-38,3.045106e-39,1.684073e-31,1.765627e-42,5.738542e-37,8.424850e-38,...,1.773181e-38,1.129799e-53,5.957149e-37,2.233045e-32,4.378826e-52,1.308611e-43,5.037324e-57,1.585090e-37,4.923648e-42,2.064426e-41
5,2.094871e-38,2.370403e-30,5.429952e-44,2.406622e-26,5.360442e-33,2.435586e-34,1.906697e-31,1.428424e-31,3.799095e-41,5.226592e-33,...,3.256236e-29,1.000895e-44,1.401308e-37,1.382683e-34,1.372013e-44,1.373490e-36,5.675446e-48,2.146279e-40,1.785248e-37,1.537410e-44
6,2.025010e-33,1.097793e-26,2.727826e-31,2.065348e-25,4.392595e-28,1.472196e-32,2.643262e-26,1.749217e-30,1.119974e-30,2.381682e-30,...,1.079099e-30,2.604776e-39,1.081522e-29,1.968268e-27,1.876288e-38,3.784163e-33,3.206275e-42,6.824818e-30,1.698159e-32,6.048971e-35
7,9.579900e-40,1.954500e-23,8.273079e-32,4.009840e-30,8.544925e-27,1.021552e-34,4.297152e-26,4.459847e-33,1.596775e-35,4.018449e-34,...,8.743392e-33,1.600049e-37,1.752642e-33,3.925086e-28,1.829455e-36,6.006253e-37,3.383671e-46,3.741703e-31,5.560018e-35,1.607532e-41
8,7.298806e-33,4.856439e-31,1.511198e-42,2.137236e-24,3.024754e-33,3.272453e-29,2.289007e-34,1.450068e-30,3.598102e-38,3.647378e-29,...,3.190537e-28,5.721822e-47,1.307330e-39,6.082117e-34,1.748200e-47,6.890433e-28,6.765021e-46,4.032836e-39,2.676473e-29,8.396469e-44
9,1.550195e-40,3.325036e-34,1.635218e-42,2.729014e-22,4.866538e-38,4.317070e-30,1.129280e-35,6.082697e-37,2.961890e-38,1.418226e-31,...,2.874593e-32,7.832416e-55,3.827116e-39,1.457155e-33,2.178188e-56,5.216085e-33,8.275954e-54,8.729661e-41,2.990096e-36,5.936731e-42

In [73]:
accuracy_test = 0
for col in range(0, 10):
    for row in range(len(y_test)):
        if y_test.iloc[row, col] == 1 and output_test.iloc[col, row] >= 0.5:
            accuracy_test += 1
accuracy_test = accuracy_test/len(X_test)

In [74]:
accuracy_test

0.0